---
title: "Codebook"
subtitle: "2019"
author: "Brazil, the Americas and the World Project | 2019"
fontfamily: libertine
fontawesome: yes
fontsize: 12pt
monospace-url: yes
spacing: double
papersize: a4paper
bibliography: references.bib
biblio-style: apalike
output:
  pdf_document:
    citation_package: natbib
    fig_caption: false
    number_sections: false
    toc: true
    keep_tex: no
    template: article-template.latex
---

\newpage

# Introduction | Introdução

2014 codebook

INTERESSE



(1). Quando assiste às notícias, quão interessado você está quanto às relações do Brasil com outros países: muito interessado, um razoavelmente interessado, pouco interessado ou nada interessado?,



(2). Diga-me, por favor, quantas vezes você já viajou para fora do Brasil? (ENTREVISTADOR, ANOTE): _____________________



(3). Algum parente seu mora fora do Brasil?


(4). Você tem parentes que moravam aqui e que agora moram fora do Brasil?


(5). Você ou sua família recebem dinheiro de parentes que trabalham fora do país?


(5_1) (Sim 1), De qual pais?


CONFIANÇA E SEGURANÇA


(6_1). Em geral, você acredita que o mundo melhorou ou piorou nos últimos 10 anos? (ANOTE NA TABELA (6) 7)


(6_2). Em geral, você acredita que o mundo estará melhor ou pior nos próximos 10 anos? (ANOTE NA TABELA (6) 7)


[CARTÃO (7_1) ] (7_1) Agora vou ler uma lista de assuntos que podem ou não afetar os interesses mais importantes do Brasil nos próximos 10 anos. Diga-me, para cada um, se você considera (LEIA CADA OPÇÃO E ENTREGUE O CARTÃO)... como uma ameaça grave; uma ameaça importante mas não grave; ou como uma ameaça pouco importante para o Brasil:



[CARTÃO (7_1)]
Ameaça grave
Ameaça importante, mas não muito grave
Ameaça pouco importante
Não é uma ameaça (espontâneo)
NS
NR


O surgimento da China como potência mundial

O terrorismo internacional

O aquecimento global

O narcotráfico e o crime organizado

As epidemias como a AIDS

As armas nucleares

As guerrilhas

Os cortes no suprimento de energia / apagões

A pobreza e a fome no mundo

Os conflitos fronteiriços e as disputas territoriais

As lideranças populares

A escassez e a falta de alimentos


IDENTIDADE

(9) Você considera a entrada de idéias e costumes de outros países no Brasil um fato positivo ou negativo?


(10) Você concorda ou discorda que um estrangeiro nacionalizado possa... 
Ser eleito deputado ou senador


(11) E agora, diga-me se você concorda ou discorda que alguém com dupla nacionalidade possa... (LER A PRIMEIRA OPÇÃO, ANOTAR A RESPOSTA). E você concorda ou discorda que alguém com dupla nacionalidade possa (LER A SEGUNDA OPÇÃO, ANOTAR A RESPOSTA) - RODIZIAR

Ser eleito deputado ou senador
Ser eleito Presidente


CONHECIMENTO

(12) Por favor, diga-me o significado das siglas que você vê no seguinte cartão:

(OEA) Organização dos Estados Americanos
(ONU) Organização das Nações Unidas
(MRE) Ministério das Relações Exteriores
(FIFA) Federação Internacional de Futebol

PAPEL DO BRASIL E POLITICA EXTERIOR

(13) Em sua opinião, o que é melhor para o futuro do Brasil, ter participação ativa em assuntos mundiais, ou manter-se longe dos
assuntos mundiais?

Participação ativa

[CARTÃO (14)] (14) Gostaria que o Sr(a) me dissesse qual a importância que acredita que cada um dos seguintes objetivos deve ter para a política exterior do Brasil, ou seja, se o Sr(a) os considera muito importante, importante, pouco importante ou nada importante? (LEIA 4 OPÇÕES DE RESPOSTA. RELEIA A CHAMADA APÓS A LEITURA DE CADA 4 FRASES)















